/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XyAY7BJm1Pr
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Image from "next/image";

interface SelectPhotoProps {
  onFileChange: (file: File) => void;
  itemImage: File | null;
}

export function SelectPhoto({ onFileChange, itemImage }: SelectPhotoProps) {
  return (
    <main
      key="1"
      className="flex flex-col items-center justify-center min-h-screen py-2"
    >
      <div className="flex flex-col items-center justify-center min-h-screen py-2">
        <div className="flex items-center gap-4 mb-8">
          <Image
            alt="Karl's Image"
            className="rounded-full object-cover"
            height={100}
            src="/karl.png"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width={100}
          />
          <div>
            <h1 className="text-4xl font-bold mb-4">Hey! I&apos;m Karl</h1>
            <p className="text-lg max-w-md">
              I&apos;ll help you take back control of your wardrobe. First,
              upload a photo of a clothing item.
            </p>
          </div>
        </div>
        <div className=" mx-auto relative">
          <div className="flex justify-center items-center">
            <Image
              alt="Placeholder"
              className="rounded-lg object-cover"
              src={
                itemImage ? URL.createObjectURL(itemImage) : "/placeholder.svg"
              }
              // src={"/veste.jpg"}
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              height={400}
              width={400}
            />
            <div className="absolute bottom-4 w-full flex justify-around items-center">
              <Button
                className="w-12 h-12 flex justify-center items-center rounded-full bg-white bg-opacity-50"
                variant="outline"
              >
                <span aria-label="camera" role="img">
                  📷
                </span>
              </Button>
              <div>
                <Button
                  className="w-12 h-12 flex justify-center items-center rounded-full bg-white bg-opacity-50"
                  variant="outline"
                >
                  <Input
                    className="opacity-0 absolute z-10 w-12 "
                    type="file"
                    onChange={(e) => {
                      const file = e.target.files?.item(0);
                      if (!file) return;
                      onFileChange(file);
                    }}
                  />
                  <span aria-label="upload" role="img" className="text-xl">
                    📤
                  </span>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
