/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ECTHhqD2iDT
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function SelectPhoto2() {
  return (
    <main key="1" className="flex flex-col items-center justify-center min-h-screen py-2">
      <div className="flex flex-col items-center justify-center min-h-screen py-2">
        <h1 className="text-4xl font-bold mb-4">AI Stylist</h1>
        <p className="text-lg text-center mb-8">Upload a photo and get personalized outfit recommendations</p>
        <div className="w-full max-w-md mx-auto relative">
          <div className="flex justify-center items-center mb-4">
            <img
              alt="Placeholder"
              className="rounded-lg object-cover"
              height={200}
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width={200}
            />
            <div className="absolute bottom-4 w-full flex justify-around items-center">
              <Button
                className="w-12 h-12 flex justify-center items-center rounded-full bg-white bg-opacity-50"
                variant="outline"
              >
                <span aria-label="camera" role="img">
                  📷
                </span>
              </Button>
              <Button
                className="w-12 h-12 flex justify-center items-center rounded-full bg-white bg-opacity-50"
                variant="outline"
              >
                <Input className="opacity-0 absolute inset-0 z-10" type="file" />
                <span aria-label="upload" role="img">
                  📤
                </span>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
